version: '3.8'

services:
  postgres:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54321:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - airflow_network

networks:
  airflow_network:

volumes:
  pgdata: